# Generated by Django 5.0.3 on 2024-04-16 18:48

import CKrealestate.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(default='(402)000-0000', max_length=20)),
                ('contact_website_link', models.CharField(max_length=200)),
                ('contact_office_street_address', models.CharField(max_length=100)),
                ('contact_office_city', models.CharField(max_length=100)),
                ('contact_office_state', models.CharField(max_length=2)),
                ('contact_office_zip_code', models.CharField(default='00000', max_length=10)),
                ('contact_profile_image', models.ImageField(upload_to='uploads/')),
                ('contact_profile_description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('neighborhood_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Price_Range',
            fields=[
                ('price_range_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('price_range_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Status',
            fields=[
                ('property_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('property_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('property_street_address', models.CharField(max_length=100)),
                ('property_city', models.CharField(max_length=100)),
                ('property_state', models.CharField(max_length=2)),
                ('property_zip_code', models.CharField(default='00000', max_length=10)),
                ('property_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('property_description', models.TextField(max_length=800)),
                ('property_title', models.CharField(max_length=200)),
                ('property_area', models.PositiveIntegerField()),
                ('property_year_built', models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), CKrealestate.models.max_value_current_year])),
                ('property_bedroom_count', models.PositiveIntegerField(default=0)),
                ('property_bathroom_count', models.PositiveIntegerField(default=0)),
                ('property_featured', models.BooleanField(default=False)),
                ('property_active', models.BooleanField(default=True)),
                ('property_photo1', models.ImageField(upload_to='uploads/')),
                ('property_photo2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('property_photo3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('property_photo4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_neighborhood')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_price_range')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_status')),
                ('home_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_type')),
            ],
        ),
        migrations.CreateModel(
            name='Search_Log',
            fields=[
                ('search_log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('search_date', models.DateField(auto_now_add=True)),
                ('search_home_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_type')),
                ('search_neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_neighborhood')),
                ('search_price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_price_range')),
            ],
        ),
    ]
