# Generated by Django 5.0.3 on 2024-04-18 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CKrealestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search_log',
            name='search_home_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_type'),
        ),
        migrations.AlterField(
            model_name='search_log',
            name='search_neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_neighborhood'),
        ),
        migrations.AlterField(
            model_name='search_log',
            name='search_price_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CKrealestate.property_price_range'),
        ),
    ]
